#!/usr/bin/env bash
#bash script that creates pid file, prints infinite message, kill resistant
file=/var/run/holbertonscript.pid
echo $$ >> $file
trap 'echo I hate the kill command; sudo rm $file; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'sudo rm $file; exit' SIGQUIT
while ((1)); do
    echo "To infinity and beyond"
    sleep 2
done
