#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
counter=0
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]
    then
	echo -e "Holberton School\nHi"
    else
	echo "Holberton School"
    fi
    let counter=counter+1
done
