#!/usr/bin/env bash
#bash script that displays the time for 12 hours and 59 minutes
minutes=1
hours=0
while [ $hours -lt 13 ]; do
    echo Hour: $hours
    while [ $minutes -lt 60 ]; do
	echo $minutes
	let minutes+=1
    done
    let minutes=1
    let hours+=1
done
