#!/usr/bin/env bash
# bash script to install nginx
apt-get -y update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx restart
