#!/usr/bin/env bash
# bash script to install nginx
apt-get -y update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
rm /usr/share/nginx/html/index
service nginx restart
